name: Build and run tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
      inputs:
        use-headless:
          description: 'Run tests in headless mode'
          required: false
          default: 'true'

permissions:
  contents: write
  checks: write
  pull-requests: write

jobs:
    run-vet-clinic-tests:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4
        - name: Set up Java 21
          uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: '21'
            cache: maven

        - name: Build and test
          run: mvn -B clean verify -Dheadless.mode=${{ inputs.use-headless }}

        - name: Publish Test Report
          uses: mikepenz/action-junit-report@v5.0.0-a02
          if: ${{ !cancelled() && github.event_name == 'pull_request' }}
          with:
            report_paths: '**/target/failsafe-reports/TEST-*.xml'
            check_name: 'VetClinic Test Results'
            check_title_template: '{{TEST_NAME}}'
            summary: 'Results for VetClinic tests'
            detailed_summary: true
            check_retries: true
            include_passed: false
            comment: true
            flaky_summary: true

        - name: Deploy Serenity reports
          if: ${{ !cancelled() && github.event_name != 'pull_request' }}
          uses: JamesIves/github-pages-deploy-action@v4
          with:
            folder: target/site/serenity


